/* tslint:disable */
/* eslint-disable */
/**
 * TrustHub API
 * API pública de TrustHub
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiRestCoreAuthLoginPostRequest
 */
export interface ApiRestCoreAuthLoginPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiRestCoreAuthLoginPostRequest
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiRestCoreAuthLoginPostRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the ApiRestCoreAuthLoginPostRequest interface.
 */
export function instanceOfApiRestCoreAuthLoginPostRequest(value: object): value is ApiRestCoreAuthLoginPostRequest {
    return true;
}

export function ApiRestCoreAuthLoginPostRequestFromJSON(json: any): ApiRestCoreAuthLoginPostRequest {
    return ApiRestCoreAuthLoginPostRequestFromJSONTyped(json, false);
}

export function ApiRestCoreAuthLoginPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRestCoreAuthLoginPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function ApiRestCoreAuthLoginPostRequestToJSON(json: any): ApiRestCoreAuthLoginPostRequest {
    return ApiRestCoreAuthLoginPostRequestToJSONTyped(json, false);
}

export function ApiRestCoreAuthLoginPostRequestToJSONTyped(value?: ApiRestCoreAuthLoginPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

