/* tslint:disable */
/* eslint-disable */
/**
 * TrustHub API
 * API pública de TrustHub
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiRestCoreAuthLoginPostRequest,
} from '../models/index';
import {
    ApiRestCoreAuthLoginPostRequestFromJSON,
    ApiRestCoreAuthLoginPostRequestToJSON,
} from '../models/index';

export interface ApiRestCoreAuthLoginPostOperationRequest {
    apiRestCoreAuthLoginPostRequest: ApiRestCoreAuthLoginPostRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async apiRestCoreAuthLoginPostRaw(requestParameters: ApiRestCoreAuthLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['apiRestCoreAuthLoginPostRequest'] == null) {
            throw new runtime.RequiredError(
                'apiRestCoreAuthLoginPostRequest',
                'Required parameter "apiRestCoreAuthLoginPostRequest" was null or undefined when calling apiRestCoreAuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/rest/core/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiRestCoreAuthLoginPostRequestToJSON(requestParameters['apiRestCoreAuthLoginPostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiRestCoreAuthLoginPost(requestParameters: ApiRestCoreAuthLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiRestCoreAuthLoginPostRaw(requestParameters, initOverrides);
    }

}
